import type { Metadata } from "next";
<<<<<<< HEAD
import "./globals.css";

export const metadata: Metadata = {
  title: "Signalback — Find the signal. Know your next move.",
  description:
    "Catch the decisions, deadlines, and blockers buried in your conversations, with findings linked to their original messages.",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> aa276407a385b0cdb3cbeda3c6c2bfc8a576344c
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
<<<<<<< HEAD
    <html lang="en" className="h-full antialiased">
=======
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
>>>>>>> aa276407a385b0cdb3cbeda3c6c2bfc8a576344c
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
